revoke delete on table "public"."schema_migrations" from "anon";

revoke insert on table "public"."schema_migrations" from "anon";

revoke references on table "public"."schema_migrations" from "anon";

revoke select on table "public"."schema_migrations" from "anon";

revoke trigger on table "public"."schema_migrations" from "anon";

revoke truncate on table "public"."schema_migrations" from "anon";

revoke update on table "public"."schema_migrations" from "anon";

revoke delete on table "public"."schema_migrations" from "authenticated";

revoke insert on table "public"."schema_migrations" from "authenticated";

revoke references on table "public"."schema_migrations" from "authenticated";

revoke select on table "public"."schema_migrations" from "authenticated";

revoke trigger on table "public"."schema_migrations" from "authenticated";

revoke truncate on table "public"."schema_migrations" from "authenticated";

revoke update on table "public"."schema_migrations" from "authenticated";

revoke delete on table "public"."schema_migrations" from "service_role";

revoke insert on table "public"."schema_migrations" from "service_role";

revoke references on table "public"."schema_migrations" from "service_role";

revoke select on table "public"."schema_migrations" from "service_role";

revoke trigger on table "public"."schema_migrations" from "service_role";

revoke truncate on table "public"."schema_migrations" from "service_role";

revoke update on table "public"."schema_migrations" from "service_role";

alter table "public"."entries" drop constraint "entries_rating_check";

alter table "public"."entries" drop constraint "entries_pkey";

alter table "public"."schema_migrations" drop constraint "schema_migrations_pkey";

drop index if exists "public"."entries_pkey";

drop index if exists "public"."schema_migrations_pkey";

drop table "public"."schema_migrations";

alter table "public"."entries" drop column "food_desc";

alter table "public"."entries" drop column "rating_desc";

alter table "public"."entries" add column "created_at" timestamp with time zone not null default now();

alter table "public"."entries" add column "foodDesc" text;

alter table "public"."entries" add column "ratingDesc" text;

alter table "public"."entries" add column "userId" uuid;

alter table "public"."entries" alter column "foods" drop not null;

alter table "public"."entries" alter column "id" drop default;

alter table "public"."entries" alter column "id" add generated by default as identity;

alter table "public"."entries" alter column "id" set data type bigint using "id"::bigint;

alter table "public"."entries" alter column "title" drop not null;

alter table "public"."entries" enable row level security;

alter table "public"."users" add column "email" text;

drop sequence if exists "public"."entries_id_seq";

CREATE UNIQUE INDEX entriese_pkey ON public.entries USING btree (id);

alter table "public"."entries" add constraint "entriese_pkey" PRIMARY KEY using index "entriese_pkey";

alter table "public"."entries" add constraint "entries_userId_fkey" FOREIGN KEY ("userId") REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."entries" validate constraint "entries_userId_fkey";


